
import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cil3d,
  cil4k,
  cilAccountLogout,
  cilActionRedo,
  cilActionUndo,
  cilAddressBook,
  cilAirplaneMode,
  cilAirplaneModeOff,
  cilAirplay,
  cilAlarm,
  cilAlbum,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilAmericanFootball,
  cilAnimal,
  cilAperture,
  cilApple,
  cilApplications,
  cilApplicationsSettings,
  cilApps,
  cilAppsSettings,
  cilArrowBottom,
  cilArrowCircleBottom,
  cilArrowCircleLeft,
  cilArrowCircleRight,
  cilArrowCircleTop,
  cilArrowLeft,
  cilArrowRight,
  cilArrowThickBottom,
  cilArrowThickFromBottom,
  cilArrowThickFromLeft,
  cilArrowThickFromRight,
  cilArrowThickFromTop,
  cilArrowThickLeft,
  cilArrowThickRight,
  cilArrowThickToBottom,
  cilArrowThickToLeft,
  cilArrowThickToRight,
  cilArrowThickToTop,
  cilArrowThickTop,
  cilArrowTop,
  cilAssistiveListeningSystem,
  cilAsterisk,
  cilAsteriskCircle,
  cilAt,
  cilAudio,
  cilAudioDescription,
  cilAudioSpectrum,
  cilAvTimer,
  cilBaby,
  cilBabyCarriage,
  cilBackspace,
  cilBadge,
  cilBalanceScale,
  cilBan,
  cilBank,
  cilBarChart,
  cilBarcode,
  cilBaseball,
  cilBasket,
  cilBasketball,
  cilBath,
  cilBathroom,
  cilBattery0,
  cilBattery3,
  cilBattery5,
  cilBatteryAlert,
  cilBatteryEmpty,
  cilBatteryFull,
  cilBatterySlash,
  cilBeachAccess,
  cilBeaker,
  cilBed,
  cilBell,
  cilBellExclamation,
  cilBike,
  cilBirthdayCake,
  cilBlind,
  cilBluetooth,
  cilBlur,
  cilBlurCircular,
  cilBlurLinear,
  cilBoatAlt,
  cilBold,
  cilBolt,
  cilBoltCircle,
  cilBook,
  cilBookmark,
  cilBorderAll,
  cilBorderBottom,
  cilBorderClear,
  cilBorderHorizontal,
  cilBorderInner,
  cilBorderLeft,
  cilBorderOuter,
  cilBorderRight,
  cilBorderStyle,
  cilBorderTop,
  cilBorderVertical,
  cilBowling,
  cilBraille,
  cilBriefcase,
  cilBrightness,
  cilBritishPound,
  cilBrowser,
  cilBrush,
  cilBrushAlt,
  cilBug,
  cilBuilding,
  cilBullhorn,
  cilBurger,
  cilBurn,
  cilBusAlt,
  cilCalculator,
  cilCalendar,
  cilCalendarCheck,
  cilCamera,
  cilCameraControl,
  cilCameraRoll,
  cilCarAlt,
  cilCaretBottom,
  cilCaretLeft,
  cilCaretRight,
  cilCaretTop,
  cilCart,
  cilCash,
  cilCasino,
  cilCast,
  cilCat,
  cilCc,
  cilCenterFocus,
  cilChart,
  cilChartLine,
  cilChartPie,
  cilChatBubble,
  cilCheck,
  cilCheckAlt,
  cilCheckCircle,
  cilChevronBottom,
  cilChevronCircleDownAlt,
  cilChevronCircleLeftAlt,
  cilChevronCircleRightAlt,
  cilChevronCircleUpAlt,
  cilChevronDoubleDown,
  cilChevronDoubleLeft,
  cilChevronDoubleRight,
  cilChevronDoubleUp,
  cilChevronLeft,
  cilChevronRight,
  cilChevronTop,
  cilChild,
  cilChildFriendly,
  cilCircle,
  cilClearAll,
  cilClipboard,
  cilClock,
  cilClone,
  cilClosedCaptioning,
  cilCloud,
  cilCloudDownload,
  cilCloudUpload,
  cilCloudy,
  cilCode,
  cilCoffee,
  cilCog,
  cilColorBorder,
  cilColorFill,
  cilColorPalette,
  cilColumns,
  cilCommand,
  cilCommentBubble,
  cilCommentSquare,
  cilCompass,
  cilCompress,
  cilContact,
  cilContrast,
  cilControl,
  cilCopy,
  cilCouch,
  cilCreditCard,
  cilCrop,
  cilCropRotate,
  cilCursor,
  cilCursorMove,
  cilCut,
  cilDataTransferDown,
  cilDataTransferUp,
  cilDeaf,
  cilDelete,
  cilDescription,
  cilDevices,
  cilDialpad,
  cilDiamond,
  cilDinner,
  cilDisabled,
  cilDog,
  cilDollar,
  cilDoor,
  cilDoubleQuoteSansLeft,
  cilDoubleQuoteSansRight,
  cilDrink,
  cilDrinkAlcohol,
  cilDrop,
  cilEco,
  cilEducation,
  cilElevator,
  cilEnvelopeClosed,
  cilEnvelopeLetter,
  cilEnvelopeOpen,
  cilEqualizer,
  cilEthernet,
  cilEuro,
  cilExcerpt,
  cilExitToApp,
  cilExpandDown,
  cilExpandLeft,
  cilExpandRight,
  cilExpandUp,
  cilExposure,
  cilExternalLink,
  cilEyedropper,
  cilFace,
  cilFaceDead,
  cilFactory,
  cilFactorySlash,
  cilFastfood,
  cilFax,
  cilFeaturedPlaylist,
  cilFile,
  cilFilter,
  cilFilterFrames,
  cilFilterPhoto,
  cilFilterSquare,
  cilFilterX,
  cilFindInPage,
  cilFingerprint,
  cilFire,
  cilFlagAlt,
  cilFlightTakeoff,
  cilFlip,
  cilFlipToBack,
  cilFlipToFront,
  cilFlower,
  cilFolder,
  cilFolderOpen,
  cilFont,
  cilFootball,
  cilFork,
  cilFridge,
  cilFrown,
  cilFullscreen,
  cilFullscreenExit,
  cilFunctions,
  cilFunctionsAlt,
  cilGamepad,
  cilGarage,
  cilGem,
  cilGif,
  cilGift,
  cilGlobeAlt,
  cilGolf,
  cilGolfAlt,
  cilGradient,
  cilGrain,
  cilGraph,
  cilGrid,
  cilGridSlash,
  cilGroup,
  cilHamburgerMenu,
  cilHandPointDown,
  cilHandPointLeft,
  cilHandPointRight,
  cilHandPointUp,
  cilHandshake,
  cilHappy,
  cilHd,
  cilHdr,
  cilHeader,
  cilHeadphones,
  cilHealing,
  cilHeart,
  cilHighlighter,
  cilHighligt,
  cilHistory,
  cilHome,
  cilHospital,
  cilHotTub,
  cilHouse,
  cilHttps,
  cilImage,
  cilImageBroken,
  cilImagePlus,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilIndustry,
  cilIndustrySlash,
  cilInfinity,
  cilInfo,
  cilInput,
  cilInputHdmi,
  cilInputPower,
  cilInstitution,
  cilItalic,
  cilJustifyCenter,
  cilJustifyLeft,
  cilJustifyRight,
  cilKeyboard,
  cilLan,
  cilLanguage,
  cilLaptop,
  cilLayers,
  cilLeaf,
  cilLemon,
  cilLevelDown,
  cilLevelUp,
  cilLibrary,
  cilLibraryAdd,
  cilLibraryBuilding,
  cilLifeRing,
  cilLightbulb,
  cilLineSpacing,
  cilLineStyle,
  cilLineWeight,
  cilLink,
  cilLinkAlt,
  cilLinkBroken,
  cilList,
  cilListFilter,
  cilListHighPriority,
  cilListLowPriority,
  cilListNumbered,
  cilListNumberedRtl,
  cilListRich,
  cilLocationPin,
  cilLockLocked,
  cilLockUnlocked,
  cilLocomotive,
  cilLoop,
  cilLoop1,
  cilLoopCircular,
  cilLowVision,
  cilMagnifyingGlass,
  cilMap,
  cilMediaEject,
  cilMediaPause,
  cilMediaPlay,
  cilMediaRecord,
  cilMediaSkipBackward,
  cilMediaSkipForward,
  cilMediaStepBackward,
  cilMediaStepForward,
  cilMediaStop,
  cilMedicalCross,
  cilMeh,
  cilMemory,
  cilMenu,
  cilMic,
  cilMicrophone,
  cilMinus,
  cilMobile,
  cilMobileLandscape,
  cilMoney,
  cilMonitor,
  cilMoodBad,
  cilMoodGood,
  cilMoodVeryBad,
  cilMoodVeryGood,
  cilMoon,
  cilMouse,
  cilMouthSlash,
  cilMove,
  cilMovie,
  cilMug,
  cilMugTea,
  cilMusicNote,
  cilNewspaper,
  cilNoteAdd,
  cilNotes,
  cilObjectGroup,
  cilObjectUngroup,
  cilOpacity,
  cilOpentype,
  cilOptions,
  cilPaint,
  cilPaintBucket,
  cilPaperPlane,
  cilPaperclip,
  cilParagraph,
  cilPaw,
  cilPen,
  cilPenAlt,
  cilPenNib,
  cilPencil,
  cilPeople,
  cilPhone,
  cilPin,
  cilPizza,
  cilPlant,
  cilPlaylistAdd,
  cilPlus,
  cilPool,
  cilPowerStandby,
  cilPregnant,
  cilPrint,
  cilPushchair,
  cilPuzzle,
  cilQrCode,
  cilRain,
  cilRectangle,
  cilRecycle,
  cilReload,
  cilReportSlash,
  cilResizeBoth,
  cilResizeHeight,
  cilResizeWidth,
  cilRestaurant,
  cilRoom,
  cilRouter,
  cilRowing,
  cilRss,
  cilRuble,
  cilRunning,
  cilSad,
  cilSatelite,
  cilSave,
  cilSchool,
  cilScreenDesktop,
  cilScreenSmartphone,
  cilScrubber,
  cilSearch,
  cilSend,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareAlt,
  cilShareBoxed,
  cilShieldAlt,
  cilShortText,
  cilShower,
  cilSignLanguage,
  cilSignalCellular0,
  cilSignalCellular3,
  cilSignalCellular4,
  cilSim,
  cilSitemap,
  cilSmile,
  cilSmilePlus,
  cilSmoke,
  cilSmokeFree,
  cilSmokeSlash,
  cilSmokingRoom,
  cilSnowflake,
  cilSoccer,
  cilSofa,
  cilSortAlphaDown,
  cilSortAlphaUp,
  cilSortAscending,
  cilSortDescending,
  cilSortNumericDown,
  cilSortNumericUp,
  cilSpa,
  cilSpaceBar,
  cilSpeak,
  cilSpeaker,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilSquare,
  cilStar,
  cilStarHalf,
  cilStorage,
  cilStream,
  cilStrikethrough,
  cilSun,
  cilSwapHorizontal,
  cilSwapVertical,
  cilSwimming,
  cilSync,
  cilTablet,
  cilTag,
  cilTags,
  cilTask,
  cilTaxi,
  cilTennis,
  cilTennisBall,
  cilTerminal,
  cilTerrain,
  cilText,
  cilTextDirectionLtr,
  cilTextDirectionRtl,
  cilTextShapes,
  cilTextSize,
  cilTextSquare,
  cilTextStrike,
  cilThumbDown,
  cilThumbUp,
  cilToggleOff,
  cilToggleOn,
  cilToilet,
  cilTouchApp,
  cilTransfer,
  cilTranslate,
  cilTrash,
  cilTriangle,
  cilTruck,
  cilTv,
  cilUnderline,
  cilUsb,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserPlus,
  cilUserUnfollow,
  cilUserX,
  cilVector,
  cilVerticalAlignBottom,
  cilVerticalAlignCenter,
  cilVerticalAlignTop,
  cilVideo,
  cilVideogame,
  cilViewColumn,
  cilViewModule,
  cilViewQuilt,
  cilViewStream,
  cilVoice,
  cilVoiceOverRecord,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilWalk,
  cilWallet,
  cilWallpaper,
  cilWarning,
  cilWatch,
  cilWc,
  cilWeightlifitng,
  cilWheelchair,
  cilWifiSignal0,
  cilWifiSignal1,
  cilWifiSignal2,
  cilWifiSignal3,
  cilWifiSignal4,
  cilWifiSignalOff,
  cilWindow,
  cilWindowMaximize,
  cilWindowMinimize,
  cilWindowRestore,
  cilWrapText,
  cilX,
  cilXCircle,
  cilYen,
  cilZoom,
  cilZoomIn,
  cilZoomOut,
  // logo,
  // signet
} from '@coreui/icons';

import { signet } from './signet';
import { logo } from './logo';

export const iconSubset = {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cil3d,
  cil4k,
  cilAccountLogout,
  cilActionRedo,
  cilActionUndo,
  cilAddressBook,
  cilAirplaneMode,
  cilAirplaneModeOff,
  cilAirplay,
  cilAlarm,
  cilAlbum,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilAmericanFootball,
  cilAnimal,
  cilAperture,
  cilApple,
  cilApplications,
  cilApplicationsSettings,
  cilApps,
  cilAppsSettings,
  cilArrowBottom,
  cilArrowCircleBottom,
  cilArrowCircleLeft,
  cilArrowCircleRight,
  cilArrowCircleTop,
  cilArrowLeft,
  cilArrowRight,
  cilArrowThickBottom,
  cilArrowThickFromBottom,
  cilArrowThickFromLeft,
  cilArrowThickFromRight,
  cilArrowThickFromTop,
  cilArrowThickLeft,
  cilArrowThickRight,
  cilArrowThickToBottom,
  cilArrowThickToLeft,
  cilArrowThickToRight,
  cilArrowThickToTop,
  cilArrowThickTop,
  cilArrowTop,
  cilAssistiveListeningSystem,
  cilAsterisk,
  cilAsteriskCircle,
  cilAt,
  cilAudio,
  cilAudioDescription,
  cilAudioSpectrum,
  cilAvTimer,
  cilBaby,
  cilBabyCarriage,
  cilBackspace,
  cilBadge,
  cilBalanceScale,
  cilBan,
  cilBank,
  cilBarChart,
  cilBarcode,
  cilBaseball,
  cilBasket,
  cilBasketball,
  cilBath,
  cilBathroom,
  cilBattery0,
  cilBattery3,
  cilBattery5,
  cilBatteryAlert,
  cilBatteryEmpty,
  cilBatteryFull,
  cilBatterySlash,
  cilBeachAccess,
  cilBeaker,
  cilBed,
  cilBell,
  cilBellExclamation,
  cilBike,
  cilBirthdayCake,
  cilBlind,
  cilBluetooth,
  cilBlur,
  cilBlurCircular,
  cilBlurLinear,
  cilBoatAlt,
  cilBold,
  cilBolt,
  cilBoltCircle,
  cilBook,
  cilBookmark,
  cilBorderAll,
  cilBorderBottom,
  cilBorderClear,
  cilBorderHorizontal,
  cilBorderInner,
  cilBorderLeft,
  cilBorderOuter,
  cilBorderRight,
  cilBorderStyle,
  cilBorderTop,
  cilBorderVertical,
  cilBowling,
  cilBraille,
  cilBriefcase,
  cilBrightness,
  cilBritishPound,
  cilBrowser,
  cilBrush,
  cilBrushAlt,
  cilBug,
  cilBuilding,
  cilBullhorn,
  cilBurger,
  cilBurn,
  cilBusAlt,
  cilCalculator,
  cilCalendar,
  cilCalendarCheck,
  cilCamera,
  cilCameraControl,
  cilCameraRoll,
  cilCarAlt,
  cilCaretBottom,
  cilCaretLeft,
  cilCaretRight,
  cilCaretTop,
  cilCart,
  cilCash,
  cilCasino,
  cilCast,
  cilCat,
  cilCc,
  cilCenterFocus,
  cilChart,
  cilChartLine,
  cilChartPie,
  cilChatBubble,
  cilCheck,
  cilCheckAlt,
  cilCheckCircle,
  cilChevronBottom,
  cilChevronCircleDownAlt,
  cilChevronCircleLeftAlt,
  cilChevronCircleRightAlt,
  cilChevronCircleUpAlt,
  cilChevronDoubleDown,
  cilChevronDoubleLeft,
  cilChevronDoubleRight,
  cilChevronDoubleUp,
  cilChevronLeft,
  cilChevronRight,
  cilChevronTop,
  cilChild,
  cilChildFriendly,
  cilCircle,
  cilClearAll,
  cilClipboard,
  cilClock,
  cilClone,
  cilClosedCaptioning,
  cilCloud,
  cilCloudDownload,
  cilCloudUpload,
  cilCloudy,
  cilCode,
  cilCoffee,
  cilCog,
  cilColorBorder,
  cilColorFill,
  cilColorPalette,
  cilColumns,
  cilCommand,
  cilCommentBubble,
  cilCommentSquare,
  cilCompass,
  cilCompress,
  cilContact,
  cilContrast,
  cilControl,
  cilCopy,
  cilCouch,
  cilCreditCard,
  cilCrop,
  cilCropRotate,
  cilCursor,
  cilCursorMove,
  cilCut,
  cilDataTransferDown,
  cilDataTransferUp,
  cilDeaf,
  cilDelete,
  cilDescription,
  cilDevices,
  cilDialpad,
  cilDiamond,
  cilDinner,
  cilDisabled,
  cilDog,
  cilDollar,
  cilDoor,
  cilDoubleQuoteSansLeft,
  cilDoubleQuoteSansRight,
  cilDrink,
  cilDrinkAlcohol,
  cilDrop,
  cilEco,
  cilEducation,
  cilElevator,
  cilEnvelopeClosed,
  cilEnvelopeLetter,
  cilEnvelopeOpen,
  cilEqualizer,
  cilEthernet,
  cilEuro,
  cilExcerpt,
  cilExitToApp,
  cilExpandDown,
  cilExpandLeft,
  cilExpandRight,
  cilExpandUp,
  cilExposure,
  cilExternalLink,
  cilEyedropper,
  cilFace,
  cilFaceDead,
  cilFactory,
  cilFactorySlash,
  cilFastfood,
  cilFax,
  cilFeaturedPlaylist,
  cilFile,
  cilFilter,
  cilFilterFrames,
  cilFilterPhoto,
  cilFilterSquare,
  cilFilterX,
  cilFindInPage,
  cilFingerprint,
  cilFire,
  cilFlagAlt,
  cilFlightTakeoff,
  cilFlip,
  cilFlipToBack,
  cilFlipToFront,
  cilFlower,
  cilFolder,
  cilFolderOpen,
  cilFont,
  cilFootball,
  cilFork,
  cilFridge,
  cilFrown,
  cilFullscreen,
  cilFullscreenExit,
  cilFunctions,
  cilFunctionsAlt,
  cilGamepad,
  cilGarage,
  cilGem,
  cilGif,
  cilGift,
  cilGlobeAlt,
  cilGolf,
  cilGolfAlt,
  cilGradient,
  cilGrain,
  cilGraph,
  cilGrid,
  cilGridSlash,
  cilGroup,
  cilHamburgerMenu,
  cilHandPointDown,
  cilHandPointLeft,
  cilHandPointRight,
  cilHandPointUp,
  cilHandshake,
  cilHappy,
  cilHd,
  cilHdr,
  cilHeader,
  cilHeadphones,
  cilHealing,
  cilHeart,
  cilHighlighter,
  cilHighligt,
  cilHistory,
  cilHome,
  cilHospital,
  cilHotTub,
  cilHouse,
  cilHttps,
  cilImage,
  cilImageBroken,
  cilImagePlus,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilIndustry,
  cilIndustrySlash,
  cilInfinity,
  cilInfo,
  cilInput,
  cilInputHdmi,
  cilInputPower,
  cilInstitution,
  cilItalic,
  cilJustifyCenter,
  cilJustifyLeft,
  cilJustifyRight,
  cilKeyboard,
  cilLan,
  cilLanguage,
  cilLaptop,
  cilLayers,
  cilLeaf,
  cilLemon,
  cilLevelDown,
  cilLevelUp,
  cilLibrary,
  cilLibraryAdd,
  cilLibraryBuilding,
  cilLifeRing,
  cilLightbulb,
  cilLineSpacing,
  cilLineStyle,
  cilLineWeight,
  cilLink,
  cilLinkAlt,
  cilLinkBroken,
  cilList,
  cilListFilter,
  cilListHighPriority,
  cilListLowPriority,
  cilListNumbered,
  cilListNumberedRtl,
  cilListRich,
  cilLocationPin,
  cilLockLocked,
  cilLockUnlocked,
  cilLocomotive,
  cilLoop,
  cilLoop1,
  cilLoopCircular,
  cilLowVision,
  cilMagnifyingGlass,
  cilMap,
  cilMediaEject,
  cilMediaPause,
  cilMediaPlay,
  cilMediaRecord,
  cilMediaSkipBackward,
  cilMediaSkipForward,
  cilMediaStepBackward,
  cilMediaStepForward,
  cilMediaStop,
  cilMedicalCross,
  cilMeh,
  cilMemory,
  cilMenu,
  cilMic,
  cilMicrophone,
  cilMinus,
  cilMobile,
  cilMobileLandscape,
  cilMoney,
  cilMonitor,
  cilMoodBad,
  cilMoodGood,
  cilMoodVeryBad,
  cilMoodVeryGood,
  cilMoon,
  cilMouse,
  cilMouthSlash,
  cilMove,
  cilMovie,
  cilMug,
  cilMugTea,
  cilMusicNote,
  cilNewspaper,
  cilNoteAdd,
  cilNotes,
  cilObjectGroup,
  cilObjectUngroup,
  cilOpacity,
  cilOpentype,
  cilOptions,
  cilPaint,
  cilPaintBucket,
  cilPaperPlane,
  cilPaperclip,
  cilParagraph,
  cilPaw,
  cilPen,
  cilPenAlt,
  cilPenNib,
  cilPencil,
  cilPeople,
  cilPhone,
  cilPin,
  cilPizza,
  cilPlant,
  cilPlaylistAdd,
  cilPlus,
  cilPool,
  cilPowerStandby,
  cilPregnant,
  cilPrint,
  cilPushchair,
  cilPuzzle,
  cilQrCode,
  cilRain,
  cilRectangle,
  cilRecycle,
  cilReload,
  cilReportSlash,
  cilResizeBoth,
  cilResizeHeight,
  cilResizeWidth,
  cilRestaurant,
  cilRoom,
  cilRouter,
  cilRowing,
  cilRss,
  cilRuble,
  cilRunning,
  cilSad,
  cilSatelite,
  cilSave,
  cilSchool,
  cilScreenDesktop,
  cilScreenSmartphone,
  cilScrubber,
  cilSearch,
  cilSend,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareAlt,
  cilShareBoxed,
  cilShieldAlt,
  cilShortText,
  cilShower,
  cilSignLanguage,
  cilSignalCellular0,
  cilSignalCellular3,
  cilSignalCellular4,
  cilSim,
  cilSitemap,
  cilSmile,
  cilSmilePlus,
  cilSmoke,
  cilSmokeFree,
  cilSmokeSlash,
  cilSmokingRoom,
  cilSnowflake,
  cilSoccer,
  cilSofa,
  cilSortAlphaDown,
  cilSortAlphaUp,
  cilSortAscending,
  cilSortDescending,
  cilSortNumericDown,
  cilSortNumericUp,
  cilSpa,
  cilSpaceBar,
  cilSpeak,
  cilSpeaker,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilSquare,
  cilStar,
  cilStarHalf,
  cilStorage,
  cilStream,
  cilStrikethrough,
  cilSun,
  cilSwapHorizontal,
  cilSwapVertical,
  cilSwimming,
  cilSync,
  cilTablet,
  cilTag,
  cilTags,
  cilTask,
  cilTaxi,
  cilTennis,
  cilTennisBall,
  cilTerminal,
  cilTerrain,
  cilText,
  cilTextDirectionLtr,
  cilTextDirectionRtl,
  cilTextShapes,
  cilTextSize,
  cilTextSquare,
  cilTextStrike,
  cilThumbDown,
  cilThumbUp,
  cilToggleOff,
  cilToggleOn,
  cilToilet,
  cilTouchApp,
  cilTransfer,
  cilTranslate,
  cilTrash,
  cilTriangle,
  cilTruck,
  cilTv,
  cilUnderline,
  cilUsb,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserPlus,
  cilUserUnfollow,
  cilUserX,
  cilVector,
  cilVerticalAlignBottom,
  cilVerticalAlignCenter,
  cilVerticalAlignTop,
  cilVideo,
  cilVideogame,
  cilViewColumn,
  cilViewModule,
  cilViewQuilt,
  cilViewStream,
  cilVoice,
  cilVoiceOverRecord,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilWalk,
  cilWallet,
  cilWallpaper,
  cilWarning,
  cilWatch,
  cilWc,
  cilWeightlifitng,
  cilWheelchair,
  cilWifiSignal0,
  cilWifiSignal1,
  cilWifiSignal2,
  cilWifiSignal3,
  cilWifiSignal4,
  cilWifiSignalOff,
  cilWindow,
  cilWindowMaximize,
  cilWindowMinimize,
  cilWindowRestore,
  cilWrapText,
  cilX,
  cilXCircle,
  cilYen,
  cilZoom,
  cilZoomIn,
  cilZoomOut,
  logo,
  signet
};

export enum IconSubset {
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cil3d = 'cil3d',
  cil4k = 'cil4k',
  cilAccountLogout = 'cilAccountLogout',
  cilActionRedo = 'cilActionRedo',
  cilActionUndo = 'cilActionUndo',
  cilAddressBook = 'cilAddressBook',
  cilAirplaneMode = 'cilAirplaneMode',
  cilAirplaneModeOff = 'cilAirplaneModeOff',
  cilAirplay = 'cilAirplay',
  cilAlarm = 'cilAlarm',
  cilAlbum = 'cilAlbum',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilAmericanFootball = 'cilAmericanFootball',
  cilAnimal = 'cilAnimal',
  cilAperture = 'cilAperture',
  cilApple = 'cilApple',
  cilApplications = 'cilApplications',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilApps = 'cilApps',
  cilAppsSettings = 'cilAppsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowCircleBottom = 'cilArrowCircleBottom',
  cilArrowCircleLeft = 'cilArrowCircleLeft',
  cilArrowCircleRight = 'cilArrowCircleRight',
  cilArrowCircleTop = 'cilArrowCircleTop',
  cilArrowLeft = 'cilArrowLeft',
  cilArrowRight = 'cilArrowRight',
  cilArrowThickBottom = 'cilArrowThickBottom',
  cilArrowThickFromBottom = 'cilArrowThickFromBottom',
  cilArrowThickFromLeft = 'cilArrowThickFromLeft',
  cilArrowThickFromRight = 'cilArrowThickFromRight',
  cilArrowThickFromTop = 'cilArrowThickFromTop',
  cilArrowThickLeft = 'cilArrowThickLeft',
  cilArrowThickRight = 'cilArrowThickRight',
  cilArrowThickToBottom = 'cilArrowThickToBottom',
  cilArrowThickToLeft = 'cilArrowThickToLeft',
  cilArrowThickToRight = 'cilArrowThickToRight',
  cilArrowThickToTop = 'cilArrowThickToTop',
  cilArrowThickTop = 'cilArrowThickTop',
  cilArrowTop = 'cilArrowTop',
  cilAssistiveListeningSystem = 'cilAssistiveListeningSystem',
  cilAsterisk = 'cilAsterisk',
  cilAsteriskCircle = 'cilAsteriskCircle',
  cilAt = 'cilAt',
  cilAudio = 'cilAudio',
  cilAudioDescription = 'cilAudioDescription',
  cilAudioSpectrum = 'cilAudioSpectrum',
  cilAvTimer = 'cilAvTimer',
  cilBaby = 'cilBaby',
  cilBabyCarriage = 'cilBabyCarriage',
  cilBackspace = 'cilBackspace',
  cilBadge = 'cilBadge',
  cilBalanceScale = 'cilBalanceScale',
  cilBan = 'cilBan',
  cilBank = 'cilBank',
  cilBarChart = 'cilBarChart',
  cilBarcode = 'cilBarcode',
  cilBaseball = 'cilBaseball',
  cilBasket = 'cilBasket',
  cilBasketball = 'cilBasketball',
  cilBath = 'cilBath',
  cilBathroom = 'cilBathroom',
  cilBattery0 = 'cilBattery0',
  cilBattery3 = 'cilBattery3',
  cilBattery5 = 'cilBattery5',
  cilBatteryAlert = 'cilBatteryAlert',
  cilBatteryEmpty = 'cilBatteryEmpty',
  cilBatteryFull = 'cilBatteryFull',
  cilBatterySlash = 'cilBatterySlash',
  cilBeachAccess = 'cilBeachAccess',
  cilBeaker = 'cilBeaker',
  cilBed = 'cilBed',
  cilBell = 'cilBell',
  cilBellExclamation = 'cilBellExclamation',
  cilBike = 'cilBike',
  cilBirthdayCake = 'cilBirthdayCake',
  cilBlind = 'cilBlind',
  cilBluetooth = 'cilBluetooth',
  cilBlur = 'cilBlur',
  cilBlurCircular = 'cilBlurCircular',
  cilBlurLinear = 'cilBlurLinear',
  cilBoatAlt = 'cilBoatAlt',
  cilBold = 'cilBold',
  cilBolt = 'cilBolt',
  cilBoltCircle = 'cilBoltCircle',
  cilBook = 'cilBook',
  cilBookmark = 'cilBookmark',
  cilBorderAll = 'cilBorderAll',
  cilBorderBottom = 'cilBorderBottom',
  cilBorderClear = 'cilBorderClear',
  cilBorderHorizontal = 'cilBorderHorizontal',
  cilBorderInner = 'cilBorderInner',
  cilBorderLeft = 'cilBorderLeft',
  cilBorderOuter = 'cilBorderOuter',
  cilBorderRight = 'cilBorderRight',
  cilBorderStyle = 'cilBorderStyle',
  cilBorderTop = 'cilBorderTop',
  cilBorderVertical = 'cilBorderVertical',
  cilBowling = 'cilBowling',
  cilBraille = 'cilBraille',
  cilBriefcase = 'cilBriefcase',
  cilBrightness = 'cilBrightness',
  cilBritishPound = 'cilBritishPound',
  cilBrowser = 'cilBrowser',
  cilBrush = 'cilBrush',
  cilBrushAlt = 'cilBrushAlt',
  cilBug = 'cilBug',
  cilBuilding = 'cilBuilding',
  cilBullhorn = 'cilBullhorn',
  cilBurger = 'cilBurger',
  cilBurn = 'cilBurn',
  cilBusAlt = 'cilBusAlt',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilCalendarCheck = 'cilCalendarCheck',
  cilCamera = 'cilCamera',
  cilCameraControl = 'cilCameraControl',
  cilCameraRoll = 'cilCameraRoll',
  cilCarAlt = 'cilCarAlt',
  cilCaretBottom = 'cilCaretBottom',
  cilCaretLeft = 'cilCaretLeft',
  cilCaretRight = 'cilCaretRight',
  cilCaretTop = 'cilCaretTop',
  cilCart = 'cilCart',
  cilCash = 'cilCash',
  cilCasino = 'cilCasino',
  cilCast = 'cilCast',
  cilCat = 'cilCat',
  cilCc = 'cilCc',
  cilCenterFocus = 'cilCenterFocus',
  cilChart = 'cilChart',
  cilChartLine = 'cilChartLine',
  cilChartPie = 'cilChartPie',
  cilChatBubble = 'cilChatBubble',
  cilCheck = 'cilCheck',
  cilCheckAlt = 'cilCheckAlt',
  cilCheckCircle = 'cilCheckCircle',
  cilChevronBottom = 'cilChevronBottom',
  cilChevronCircleDownAlt = 'cilChevronCircleDownAlt',
  cilChevronCircleLeftAlt = 'cilChevronCircleLeftAlt',
  cilChevronCircleRightAlt = 'cilChevronCircleRightAlt',
  cilChevronCircleUpAlt = 'cilChevronCircleUpAlt',
  cilChevronDoubleDown = 'cilChevronDoubleDown',
  cilChevronDoubleLeft = 'cilChevronDoubleLeft',
  cilChevronDoubleRight = 'cilChevronDoubleRight',
  cilChevronDoubleUp = 'cilChevronDoubleUp',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilChevronTop = 'cilChevronTop',
  cilChild = 'cilChild',
  cilChildFriendly = 'cilChildFriendly',
  cilCircle = 'cilCircle',
  cilClearAll = 'cilClearAll',
  cilClipboard = 'cilClipboard',
  cilClock = 'cilClock',
  cilClone = 'cilClone',
  cilClosedCaptioning = 'cilClosedCaptioning',
  cilCloud = 'cilCloud',
  cilCloudDownload = 'cilCloudDownload',
  cilCloudUpload = 'cilCloudUpload',
  cilCloudy = 'cilCloudy',
  cilCode = 'cilCode',
  cilCoffee = 'cilCoffee',
  cilCog = 'cilCog',
  cilColorBorder = 'cilColorBorder',
  cilColorFill = 'cilColorFill',
  cilColorPalette = 'cilColorPalette',
  cilColumns = 'cilColumns',
  cilCommand = 'cilCommand',
  cilCommentBubble = 'cilCommentBubble',
  cilCommentSquare = 'cilCommentSquare',
  cilCompass = 'cilCompass',
  cilCompress = 'cilCompress',
  cilContact = 'cilContact',
  cilContrast = 'cilContrast',
  cilControl = 'cilControl',
  cilCopy = 'cilCopy',
  cilCouch = 'cilCouch',
  cilCreditCard = 'cilCreditCard',
  cilCrop = 'cilCrop',
  cilCropRotate = 'cilCropRotate',
  cilCursor = 'cilCursor',
  cilCursorMove = 'cilCursorMove',
  cilCut = 'cilCut',
  cilDataTransferDown = 'cilDataTransferDown',
  cilDataTransferUp = 'cilDataTransferUp',
  cilDeaf = 'cilDeaf',
  cilDelete = 'cilDelete',
  cilDescription = 'cilDescription',
  cilDevices = 'cilDevices',
  cilDialpad = 'cilDialpad',
  cilDiamond = 'cilDiamond',
  cilDinner = 'cilDinner',
  cilDisabled = 'cilDisabled',
  cilDog = 'cilDog',
  cilDollar = 'cilDollar',
  cilDoor = 'cilDoor',
  cilDoubleQuoteSansLeft = 'cilDoubleQuoteSansLeft',
  cilDoubleQuoteSansRight = 'cilDoubleQuoteSansRight',
  cilDrink = 'cilDrink',
  cilDrinkAlcohol = 'cilDrinkAlcohol',
  cilDrop = 'cilDrop',
  cilEco = 'cilEco',
  cilEducation = 'cilEducation',
  cilElevator = 'cilElevator',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeLetter = 'cilEnvelopeLetter',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilEqualizer = 'cilEqualizer',
  cilEthernet = 'cilEthernet',
  cilEuro = 'cilEuro',
  cilExcerpt = 'cilExcerpt',
  cilExitToApp = 'cilExitToApp',
  cilExpandDown = 'cilExpandDown',
  cilExpandLeft = 'cilExpandLeft',
  cilExpandRight = 'cilExpandRight',
  cilExpandUp = 'cilExpandUp',
  cilExposure = 'cilExposure',
  cilExternalLink = 'cilExternalLink',
  cilEyedropper = 'cilEyedropper',
  cilFace = 'cilFace',
  cilFaceDead = 'cilFaceDead',
  cilFactory = 'cilFactory',
  cilFactorySlash = 'cilFactorySlash',
  cilFastfood = 'cilFastfood',
  cilFax = 'cilFax',
  cilFeaturedPlaylist = 'cilFeaturedPlaylist',
  cilFile = 'cilFile',
  cilFilter = 'cilFilter',
  cilFilterFrames = 'cilFilterFrames',
  cilFilterPhoto = 'cilFilterPhoto',
  cilFilterSquare = 'cilFilterSquare',
  cilFilterX = 'cilFilterX',
  cilFindInPage = 'cilFindInPage',
  cilFingerprint = 'cilFingerprint',
  cilFire = 'cilFire',
  cilFlagAlt = 'cilFlagAlt',
  cilFlightTakeoff = 'cilFlightTakeoff',
  cilFlip = 'cilFlip',
  cilFlipToBack = 'cilFlipToBack',
  cilFlipToFront = 'cilFlipToFront',
  cilFlower = 'cilFlower',
  cilFolder = 'cilFolder',
  cilFolderOpen = 'cilFolderOpen',
  cilFont = 'cilFont',
  cilFootball = 'cilFootball',
  cilFork = 'cilFork',
  cilFridge = 'cilFridge',
  cilFrown = 'cilFrown',
  cilFullscreen = 'cilFullscreen',
  cilFullscreenExit = 'cilFullscreenExit',
  cilFunctions = 'cilFunctions',
  cilFunctionsAlt = 'cilFunctionsAlt',
  cilGamepad = 'cilGamepad',
  cilGarage = 'cilGarage',
  cilGem = 'cilGem',
  cilGif = 'cilGif',
  cilGift = 'cilGift',
  cilGlobeAlt = 'cilGlobeAlt',
  cilGolf = 'cilGolf',
  cilGolfAlt = 'cilGolfAlt',
  cilGradient = 'cilGradient',
  cilGrain = 'cilGrain',
  cilGraph = 'cilGraph',
  cilGrid = 'cilGrid',
  cilGridSlash = 'cilGridSlash',
  cilGroup = 'cilGroup',
  cilHamburgerMenu = 'cilHamburgerMenu',
  cilHandPointDown = 'cilHandPointDown',
  cilHandPointLeft = 'cilHandPointLeft',
  cilHandPointRight = 'cilHandPointRight',
  cilHandPointUp = 'cilHandPointUp',
  cilHandshake = 'cilHandshake',
  cilHappy = 'cilHappy',
  cilHd = 'cilHd',
  cilHdr = 'cilHdr',
  cilHeader = 'cilHeader',
  cilHeadphones = 'cilHeadphones',
  cilHealing = 'cilHealing',
  cilHeart = 'cilHeart',
  cilHighlighter = 'cilHighlighter',
  cilHighligt = 'cilHighligt',
  cilHistory = 'cilHistory',
  cilHome = 'cilHome',
  cilHospital = 'cilHospital',
  cilHotTub = 'cilHotTub',
  cilHouse = 'cilHouse',
  cilHttps = 'cilHttps',
  cilImage = 'cilImage',
  cilImageBroken = 'cilImageBroken',
  cilImagePlus = 'cilImagePlus',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilIndustry = 'cilIndustry',
  cilIndustrySlash = 'cilIndustrySlash',
  cilInfinity = 'cilInfinity',
  cilInfo = 'cilInfo',
  cilInput = 'cilInput',
  cilInputHdmi = 'cilInputHdmi',
  cilInputPower = 'cilInputPower',
  cilInstitution = 'cilInstitution',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilJustifyLeft = 'cilJustifyLeft',
  cilJustifyRight = 'cilJustifyRight',
  cilKeyboard = 'cilKeyboard',
  cilLan = 'cilLan',
  cilLanguage = 'cilLanguage',
  cilLaptop = 'cilLaptop',
  cilLayers = 'cilLayers',
  cilLeaf = 'cilLeaf',
  cilLemon = 'cilLemon',
  cilLevelDown = 'cilLevelDown',
  cilLevelUp = 'cilLevelUp',
  cilLibrary = 'cilLibrary',
  cilLibraryAdd = 'cilLibraryAdd',
  cilLibraryBuilding = 'cilLibraryBuilding',
  cilLifeRing = 'cilLifeRing',
  cilLightbulb = 'cilLightbulb',
  cilLineSpacing = 'cilLineSpacing',
  cilLineStyle = 'cilLineStyle',
  cilLineWeight = 'cilLineWeight',
  cilLink = 'cilLink',
  cilLinkAlt = 'cilLinkAlt',
  cilLinkBroken = 'cilLinkBroken',
  cilList = 'cilList',
  cilListFilter = 'cilListFilter',
  cilListHighPriority = 'cilListHighPriority',
  cilListLowPriority = 'cilListLowPriority',
  cilListNumbered = 'cilListNumbered',
  cilListNumberedRtl = 'cilListNumberedRtl',
  cilListRich = 'cilListRich',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilLockUnlocked = 'cilLockUnlocked',
  cilLocomotive = 'cilLocomotive',
  cilLoop = 'cilLoop',
  cilLoop1 = 'cilLoop1',
  cilLoopCircular = 'cilLoopCircular',
  cilLowVision = 'cilLowVision',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaEject = 'cilMediaEject',
  cilMediaPause = 'cilMediaPause',
  cilMediaPlay = 'cilMediaPlay',
  cilMediaRecord = 'cilMediaRecord',
  cilMediaSkipBackward = 'cilMediaSkipBackward',
  cilMediaSkipForward = 'cilMediaSkipForward',
  cilMediaStepBackward = 'cilMediaStepBackward',
  cilMediaStepForward = 'cilMediaStepForward',
  cilMediaStop = 'cilMediaStop',
  cilMedicalCross = 'cilMedicalCross',
  cilMeh = 'cilMeh',
  cilMemory = 'cilMemory',
  cilMenu = 'cilMenu',
  cilMic = 'cilMic',
  cilMicrophone = 'cilMicrophone',
  cilMinus = 'cilMinus',
  cilMobile = 'cilMobile',
  cilMobileLandscape = 'cilMobileLandscape',
  cilMoney = 'cilMoney',
  cilMonitor = 'cilMonitor',
  cilMoodBad = 'cilMoodBad',
  cilMoodGood = 'cilMoodGood',
  cilMoodVeryBad = 'cilMoodVeryBad',
  cilMoodVeryGood = 'cilMoodVeryGood',
  cilMoon = 'cilMoon',
  cilMouse = 'cilMouse',
  cilMouthSlash = 'cilMouthSlash',
  cilMove = 'cilMove',
  cilMovie = 'cilMovie',
  cilMug = 'cilMug',
  cilMugTea = 'cilMugTea',
  cilMusicNote = 'cilMusicNote',
  cilNewspaper = 'cilNewspaper',
  cilNoteAdd = 'cilNoteAdd',
  cilNotes = 'cilNotes',
  cilObjectGroup = 'cilObjectGroup',
  cilObjectUngroup = 'cilObjectUngroup',
  cilOpacity = 'cilOpacity',
  cilOpentype = 'cilOpentype',
  cilOptions = 'cilOptions',
  cilPaint = 'cilPaint',
  cilPaintBucket = 'cilPaintBucket',
  cilPaperPlane = 'cilPaperPlane',
  cilPaperclip = 'cilPaperclip',
  cilParagraph = 'cilParagraph',
  cilPaw = 'cilPaw',
  cilPen = 'cilPen',
  cilPenAlt = 'cilPenAlt',
  cilPenNib = 'cilPenNib',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPhone = 'cilPhone',
  cilPin = 'cilPin',
  cilPizza = 'cilPizza',
  cilPlant = 'cilPlant',
  cilPlaylistAdd = 'cilPlaylistAdd',
  cilPlus = 'cilPlus',
  cilPool = 'cilPool',
  cilPowerStandby = 'cilPowerStandby',
  cilPregnant = 'cilPregnant',
  cilPrint = 'cilPrint',
  cilPushchair = 'cilPushchair',
  cilPuzzle = 'cilPuzzle',
  cilQrCode = 'cilQrCode',
  cilRain = 'cilRain',
  cilRectangle = 'cilRectangle',
  cilRecycle = 'cilRecycle',
  cilReload = 'cilReload',
  cilReportSlash = 'cilReportSlash',
  cilResizeBoth = 'cilResizeBoth',
  cilResizeHeight = 'cilResizeHeight',
  cilResizeWidth = 'cilResizeWidth',
  cilRestaurant = 'cilRestaurant',
  cilRoom = 'cilRoom',
  cilRouter = 'cilRouter',
  cilRowing = 'cilRowing',
  cilRss = 'cilRss',
  cilRuble = 'cilRuble',
  cilRunning = 'cilRunning',
  cilSad = 'cilSad',
  cilSatelite = 'cilSatelite',
  cilSave = 'cilSave',
  cilSchool = 'cilSchool',
  cilScreenDesktop = 'cilScreenDesktop',
  cilScreenSmartphone = 'cilScreenSmartphone',
  cilScrubber = 'cilScrubber',
  cilSearch = 'cilSearch',
  cilSend = 'cilSend',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareAlt = 'cilShareAlt',
  cilShareBoxed = 'cilShareBoxed',
  cilShieldAlt = 'cilShieldAlt',
  cilShortText = 'cilShortText',
  cilShower = 'cilShower',
  cilSignLanguage = 'cilSignLanguage',
  cilSignalCellular0 = 'cilSignalCellular0',
  cilSignalCellular3 = 'cilSignalCellular3',
  cilSignalCellular4 = 'cilSignalCellular4',
  cilSim = 'cilSim',
  cilSitemap = 'cilSitemap',
  cilSmile = 'cilSmile',
  cilSmilePlus = 'cilSmilePlus',
  cilSmoke = 'cilSmoke',
  cilSmokeFree = 'cilSmokeFree',
  cilSmokeSlash = 'cilSmokeSlash',
  cilSmokingRoom = 'cilSmokingRoom',
  cilSnowflake = 'cilSnowflake',
  cilSoccer = 'cilSoccer',
  cilSofa = 'cilSofa',
  cilSortAlphaDown = 'cilSortAlphaDown',
  cilSortAlphaUp = 'cilSortAlphaUp',
  cilSortAscending = 'cilSortAscending',
  cilSortDescending = 'cilSortDescending',
  cilSortNumericDown = 'cilSortNumericDown',
  cilSortNumericUp = 'cilSortNumericUp',
  cilSpa = 'cilSpa',
  cilSpaceBar = 'cilSpaceBar',
  cilSpeak = 'cilSpeak',
  cilSpeaker = 'cilSpeaker',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilSquare = 'cilSquare',
  cilStar = 'cilStar',
  cilStarHalf = 'cilStarHalf',
  cilStorage = 'cilStorage',
  cilStream = 'cilStream',
  cilStrikethrough = 'cilStrikethrough',
  cilSun = 'cilSun',
  cilSwapHorizontal = 'cilSwapHorizontal',
  cilSwapVertical = 'cilSwapVertical',
  cilSwimming = 'cilSwimming',
  cilSync = 'cilSync',
  cilTablet = 'cilTablet',
  cilTag = 'cilTag',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTaxi = 'cilTaxi',
  cilTennis = 'cilTennis',
  cilTennisBall = 'cilTennisBall',
  cilTerminal = 'cilTerminal',
  cilTerrain = 'cilTerrain',
  cilText = 'cilText',
  cilTextDirectionLtr = 'cilTextDirectionLtr',
  cilTextDirectionRtl = 'cilTextDirectionRtl',
  cilTextShapes = 'cilTextShapes',
  cilTextSize = 'cilTextSize',
  cilTextSquare = 'cilTextSquare',
  cilTextStrike = 'cilTextStrike',
  cilThumbDown = 'cilThumbDown',
  cilThumbUp = 'cilThumbUp',
  cilToggleOff = 'cilToggleOff',
  cilToggleOn = 'cilToggleOn',
  cilToilet = 'cilToilet',
  cilTouchApp = 'cilTouchApp',
  cilTransfer = 'cilTransfer',
  cilTranslate = 'cilTranslate',
  cilTrash = 'cilTrash',
  cilTriangle = 'cilTriangle',
  cilTruck = 'cilTruck',
  cilTv = 'cilTv',
  cilUnderline = 'cilUnderline',
  cilUsb = 'cilUsb',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserPlus = 'cilUserPlus',
  cilUserUnfollow = 'cilUserUnfollow',
  cilUserX = 'cilUserX',
  cilVector = 'cilVector',
  cilVerticalAlignBottom = 'cilVerticalAlignBottom',
  cilVerticalAlignCenter = 'cilVerticalAlignCenter',
  cilVerticalAlignTop = 'cilVerticalAlignTop',
  cilVideo = 'cilVideo',
  cilVideogame = 'cilVideogame',
  cilViewColumn = 'cilViewColumn',
  cilViewModule = 'cilViewModule',
  cilViewQuilt = 'cilViewQuilt',
  cilViewStream = 'cilViewStream',
  cilVoice = 'cilVoice',
  cilVoiceOverRecord = 'cilVoiceOverRecord',
  cilVolumeHigh = 'cilVolumeHigh',
  cilVolumeLow = 'cilVolumeLow',
  cilVolumeOff = 'cilVolumeOff',
  cilWalk = 'cilWalk',
  cilWallet = 'cilWallet',
  cilWallpaper = 'cilWallpaper',
  cilWarning = 'cilWarning',
  cilWatch = 'cilWatch',
  cilWc = 'cilWc',
  cilWeightlifitng = 'cilWeightlifitng',
  cilWheelchair = 'cilWheelchair',
  cilWifiSignal0 = 'cilWifiSignal0',
  cilWifiSignal1 = 'cilWifiSignal1',
  cilWifiSignal2 = 'cilWifiSignal2',
  cilWifiSignal3 = 'cilWifiSignal3',
  cilWifiSignal4 = 'cilWifiSignal4',
  cilWifiSignalOff = 'cilWifiSignalOff',
  cilWindow = 'cilWindow',
  cilWindowMaximize = 'cilWindowMaximize',
  cilWindowMinimize = 'cilWindowMinimize',
  cilWindowRestore = 'cilWindowRestore',
  cilWrapText = 'cilWrapText',
  cilX = 'cilX',
  cilXCircle = 'cilXCircle',
  cilYen = 'cilYen',
  cilZoom = 'cilZoom',
  cilZoomIn = 'cilZoomIn',
  cilZoomOut = 'cilZoomOut',
  logo = 'logo',
  signet = 'signet'
}
