server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /ibc-services/v1/api/v1/ibc {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /cmn-services/v1/CMN {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /adm-services/v1/ADM {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /idm-services/v1/IDM {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /sec-services/v1/SEC {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /bkp-services/v1/BKP {
        proxy_pass https://niiseapis-dev.awanheitech.com;
        proxy_ssl_verify off;
    }

    location /api/v1/IDM {
        proxy_pass http://localhost:8080;
        proxy_ssl_verify off;
    }
    # Allow CORS (optional, only if required)
    # location /api/ {
    #     proxy_pass http://backend-service:8080;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }
}
